### ISSUE TITLE
what happens when a directory already exists?

### ISSUE THREAD

**Issue by sksar** [bpedro/node-fs#13]
suppose i do this 
`fs.mkdirSync('/tmp/example_sync/first/second/third/fourth/fifth', 0777, true);`
then this
`fs.mkdirSync('/tmp/example_sync/first/second/third/fourth/fifth/sixth/seventh', 0777, true);`
and then this
`fs.mkdirSync('/tmp/example_sync/first/second/third/', 0777, true);`

what will happen? will any exception be thrown that file already exists??

if yes then how can i get it such that the node-fs will ignore and just continue executing and creating the rest of the folders(if passed as arg)..

**Comment by bpedro** [comment]
Hi @sksar,

Thanks for the comment. No exceptions will be thrown if the path already exists.
